// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/nftfactory/v1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	ClassAuthorities     []ClassAuthority `protobuf:"bytes,1,rep,name=class_authorities,json=classAuthorities,proto3" json:"class_authorities"`
	CreatorClasses       []CreatorClass   `protobuf:"bytes,2,rep,name=creator_classes,json=creatorClasses,proto3" json:"creator_classes"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7330075d7b28b851, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetClassAuthorities() []ClassAuthority {
	if m != nil {
		return m.ClassAuthorities
	}
	return nil
}

func (m *GenesisState) GetCreatorClasses() []CreatorClass {
	if m != nil {
		return m.CreatorClasses
	}
	return nil
}

type ClassAuthority struct {
	ClassId              string   `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Admin                string   `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassAuthority) Reset()         { *m = ClassAuthority{} }
func (m *ClassAuthority) String() string { return proto.CompactTextString(m) }
func (*ClassAuthority) ProtoMessage()    {}
func (*ClassAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_7330075d7b28b851, []int{1}
}
func (m *ClassAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassAuthority.Unmarshal(m, b)
}
func (m *ClassAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassAuthority.Marshal(b, m, deterministic)
}
func (m *ClassAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassAuthority.Merge(m, src)
}
func (m *ClassAuthority) XXX_Size() int {
	return xxx_messageInfo_ClassAuthority.Size(m)
}
func (m *ClassAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_ClassAuthority proto.InternalMessageInfo

func (m *ClassAuthority) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *ClassAuthority) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

type CreatorClass struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ClassId              string   `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatorClass) Reset()         { *m = CreatorClass{} }
func (m *CreatorClass) String() string { return proto.CompactTextString(m) }
func (*CreatorClass) ProtoMessage()    {}
func (*CreatorClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_7330075d7b28b851, []int{2}
}
func (m *CreatorClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatorClass.Unmarshal(m, b)
}
func (m *CreatorClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatorClass.Marshal(b, m, deterministic)
}
func (m *CreatorClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatorClass.Merge(m, src)
}
func (m *CreatorClass) XXX_Size() int {
	return xxx_messageInfo_CreatorClass.Size(m)
}
func (m *CreatorClass) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatorClass.DiscardUnknown(m)
}

var xxx_messageInfo_CreatorClass proto.InternalMessageInfo

func (m *CreatorClass) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CreatorClass) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "retrochain.nftfactory.v1.GenesisState")
	proto.RegisterType((*ClassAuthority)(nil), "retrochain.nftfactory.v1.ClassAuthority")
	proto.RegisterType((*CreatorClass)(nil), "retrochain.nftfactory.v1.CreatorClass")
}

func init() {
	proto.RegisterFile("retrochain/nftfactory/v1/genesis.proto", fileDescriptor_7330075d7b28b851)
}

var fileDescriptor_7330075d7b28b851 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x4e, 0xc3, 0x30,
	0x18, 0x24, 0xe5, 0xa7, 0x60, 0xaa, 0x02, 0x56, 0x07, 0xb7, 0x12, 0x6a, 0x95, 0xa1, 0xca, 0x82,
	0xa3, 0x96, 0x27, 0x68, 0x18, 0x10, 0x6b, 0x2a, 0x16, 0x2a, 0x14, 0x19, 0xc7, 0x4d, 0x2d, 0xd1,
	0xb8, 0xf2, 0x67, 0x2a, 0xf2, 0x5e, 0x3c, 0x01, 0x13, 0x33, 0x0f, 0xc0, 0xb3, 0xa0, 0xd8, 0x41,
	0x4d, 0x06, 0xba, 0xf9, 0x3b, 0xdf, 0xdd, 0x77, 0xf6, 0xa1, 0xb1, 0x16, 0x46, 0x2b, 0xbe, 0x62,
	0x32, 0x0f, 0xf3, 0xa5, 0x59, 0x32, 0x6e, 0x94, 0x2e, 0xc2, 0xed, 0x24, 0xcc, 0x44, 0x2e, 0x40,
	0x02, 0xdd, 0x68, 0x65, 0x14, 0x26, 0x3b, 0x1e, 0xdd, 0xf1, 0xe8, 0x76, 0x32, 0xe8, 0x73, 0x05,
	0x6b, 0x05, 0x89, 0xe5, 0x85, 0x6e, 0x70, 0xa2, 0x41, 0x2f, 0x53, 0x99, 0x72, 0x78, 0x79, 0x72,
	0xa8, 0xff, 0xe9, 0xa1, 0xce, 0xbd, 0x33, 0x9f, 0x1b, 0x66, 0x04, 0x5e, 0xa0, 0x2b, 0xfe, 0xca,
	0x00, 0x12, 0xf6, 0x66, 0x56, 0x4a, 0x4b, 0x23, 0x05, 0x10, 0x6f, 0x74, 0x18, 0x9c, 0x4f, 0x03,
	0xfa, 0xdf, 0x5e, 0x7a, 0x57, 0x4a, 0x66, 0x95, 0xa2, 0x88, 0x8e, 0xbe, 0x7e, 0x86, 0x07, 0xf1,
	0x25, 0xaf, 0xa3, 0x52, 0x00, 0x7e, 0x44, 0x17, 0x5c, 0x0b, 0x66, 0x94, 0x4e, 0xec, 0x9d, 0x00,
	0xd2, 0xb2, 0xd6, 0xe3, 0x3d, 0xd6, 0x4e, 0x60, 0x37, 0x54, 0xc6, 0x5d, 0x5e, 0xc3, 0x04, 0xf8,
	0x0b, 0xd4, 0x6d, 0x06, 0xc0, 0x7d, 0x74, 0xea, 0x5e, 0x21, 0x53, 0xe2, 0x8d, 0xbc, 0xe0, 0x2c,
	0x6e, 0xdb, 0xf9, 0x21, 0xc5, 0x14, 0x1d, 0xb3, 0x74, 0x2d, 0x73, 0xd2, 0x2a, 0xf1, 0x88, 0x7c,
	0x7f, 0xdc, 0xf4, 0xaa, 0x8f, 0x9a, 0xa5, 0xa9, 0x16, 0x00, 0x73, 0xa3, 0x65, 0x9e, 0xc5, 0x8e,
	0xe6, 0x3f, 0xa3, 0x4e, 0x3d, 0x02, 0x9e, 0xa2, 0x76, 0xb5, 0xde, 0x39, 0xef, 0x71, 0xf8, 0x23,
	0x36, 0xe2, 0xb4, 0x1a, 0x71, 0xa2, 0xe1, 0xd3, 0x75, 0xad, 0xf5, 0xf7, 0x7a, 0xef, 0xa6, 0xd8,
	0x08, 0x78, 0x39, 0xb1, 0x45, 0xdd, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x63, 0xf2, 0x62, 0x99,
	0x1d, 0x02, 0x00, 0x00,
}
