// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/nftfactory/module/v1/module.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "cosmossdk.io/api/cosmos/app/v1alpha1"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Module is the config object for the nftfactory module.
type Module struct {
	// authority defines the custom module authority.
	// If not set, defaults to the governance module.
	Authority            string   `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_67af126377c88973, []int{0}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func init() {
	proto.RegisterType((*Module)(nil), "retrochain.nftfactory.module.v1.Module")
}

func init() {
	proto.RegisterFile("retrochain/nftfactory/module/v1/module.proto", fileDescriptor_67af126377c88973)
}

var fileDescriptor_67af126377c88973 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x29, 0x4a, 0x2d, 0x29,
	0xca, 0x4f, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0xcf, 0x4b, 0x2b, 0x49, 0x4b, 0x4c, 0x2e, 0xc9, 0x2f,
	0xaa, 0xd4, 0xcf, 0xcd, 0x4f, 0x29, 0xcd, 0x49, 0xd5, 0x2f, 0x33, 0x84, 0xb2, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0xe4, 0x11, 0xaa, 0xf5, 0x10, 0xaa, 0xf5, 0xa0, 0x6a, 0xca, 0x0c, 0xa5,
	0x14, 0x92, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xf5, 0x13, 0x0b, 0x0a, 0xf4, 0xcb, 0x0c, 0x13, 0x73,
	0x0a, 0x32, 0x12, 0x51, 0x8d, 0x50, 0xf2, 0xe3, 0x62, 0xf3, 0x05, 0xf3, 0x85, 0x64, 0xb8, 0x38,
	0x13, 0x4b, 0x4b, 0x32, 0xf2, 0x8b, 0x32, 0x4b, 0x2a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x10, 0x02, 0x56, 0x6a, 0xbb, 0x0e, 0x4c, 0xbb, 0xc5, 0xa8, 0xc0, 0x25, 0x87, 0xe4, 0xc0, 0x0a,
	0x4c, 0x27, 0x3a, 0xc9, 0x47, 0xc9, 0xe2, 0x52, 0x51, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06,
	0xb6, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x76, 0x9d, 0xa8, 0xb6, 0xea, 0x00, 0x00, 0x00,
}
