// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/nftfactory/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryClassAuthorityMetadataRequest struct {
	ClassId              string   `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClassAuthorityMetadataRequest) Reset()         { *m = QueryClassAuthorityMetadataRequest{} }
func (m *QueryClassAuthorityMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClassAuthorityMetadataRequest) ProtoMessage()    {}
func (*QueryClassAuthorityMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69422d58e61ed49f, []int{0}
}
func (m *QueryClassAuthorityMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClassAuthorityMetadataRequest.Unmarshal(m, b)
}
func (m *QueryClassAuthorityMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClassAuthorityMetadataRequest.Marshal(b, m, deterministic)
}
func (m *QueryClassAuthorityMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassAuthorityMetadataRequest.Merge(m, src)
}
func (m *QueryClassAuthorityMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_QueryClassAuthorityMetadataRequest.Size(m)
}
func (m *QueryClassAuthorityMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassAuthorityMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassAuthorityMetadataRequest proto.InternalMessageInfo

func (m *QueryClassAuthorityMetadataRequest) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

type QueryClassAuthorityMetadataResponse struct {
	AuthorityMetadata    *ClassAuthorityMetadata `protobuf:"bytes,1,opt,name=authority_metadata,json=authorityMetadata,proto3" json:"authority_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QueryClassAuthorityMetadataResponse) Reset()         { *m = QueryClassAuthorityMetadataResponse{} }
func (m *QueryClassAuthorityMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClassAuthorityMetadataResponse) ProtoMessage()    {}
func (*QueryClassAuthorityMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69422d58e61ed49f, []int{1}
}
func (m *QueryClassAuthorityMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClassAuthorityMetadataResponse.Unmarshal(m, b)
}
func (m *QueryClassAuthorityMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClassAuthorityMetadataResponse.Marshal(b, m, deterministic)
}
func (m *QueryClassAuthorityMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassAuthorityMetadataResponse.Merge(m, src)
}
func (m *QueryClassAuthorityMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_QueryClassAuthorityMetadataResponse.Size(m)
}
func (m *QueryClassAuthorityMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassAuthorityMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassAuthorityMetadataResponse proto.InternalMessageInfo

func (m *QueryClassAuthorityMetadataResponse) GetAuthorityMetadata() *ClassAuthorityMetadata {
	if m != nil {
		return m.AuthorityMetadata
	}
	return nil
}

type ClassAuthorityMetadata struct {
	Admin                string   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassAuthorityMetadata) Reset()         { *m = ClassAuthorityMetadata{} }
func (m *ClassAuthorityMetadata) String() string { return proto.CompactTextString(m) }
func (*ClassAuthorityMetadata) ProtoMessage()    {}
func (*ClassAuthorityMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_69422d58e61ed49f, []int{2}
}
func (m *ClassAuthorityMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassAuthorityMetadata.Unmarshal(m, b)
}
func (m *ClassAuthorityMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassAuthorityMetadata.Marshal(b, m, deterministic)
}
func (m *ClassAuthorityMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassAuthorityMetadata.Merge(m, src)
}
func (m *ClassAuthorityMetadata) XXX_Size() int {
	return xxx_messageInfo_ClassAuthorityMetadata.Size(m)
}
func (m *ClassAuthorityMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassAuthorityMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClassAuthorityMetadata proto.InternalMessageInfo

func (m *ClassAuthorityMetadata) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

type QueryClassesFromCreatorRequest struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClassesFromCreatorRequest) Reset()         { *m = QueryClassesFromCreatorRequest{} }
func (m *QueryClassesFromCreatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClassesFromCreatorRequest) ProtoMessage()    {}
func (*QueryClassesFromCreatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69422d58e61ed49f, []int{3}
}
func (m *QueryClassesFromCreatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClassesFromCreatorRequest.Unmarshal(m, b)
}
func (m *QueryClassesFromCreatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClassesFromCreatorRequest.Marshal(b, m, deterministic)
}
func (m *QueryClassesFromCreatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesFromCreatorRequest.Merge(m, src)
}
func (m *QueryClassesFromCreatorRequest) XXX_Size() int {
	return xxx_messageInfo_QueryClassesFromCreatorRequest.Size(m)
}
func (m *QueryClassesFromCreatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesFromCreatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesFromCreatorRequest proto.InternalMessageInfo

func (m *QueryClassesFromCreatorRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryClassesFromCreatorResponse struct {
	ClassIds             []string `protobuf:"bytes,1,rep,name=class_ids,json=classIds,proto3" json:"class_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClassesFromCreatorResponse) Reset()         { *m = QueryClassesFromCreatorResponse{} }
func (m *QueryClassesFromCreatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClassesFromCreatorResponse) ProtoMessage()    {}
func (*QueryClassesFromCreatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69422d58e61ed49f, []int{4}
}
func (m *QueryClassesFromCreatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClassesFromCreatorResponse.Unmarshal(m, b)
}
func (m *QueryClassesFromCreatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClassesFromCreatorResponse.Marshal(b, m, deterministic)
}
func (m *QueryClassesFromCreatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesFromCreatorResponse.Merge(m, src)
}
func (m *QueryClassesFromCreatorResponse) XXX_Size() int {
	return xxx_messageInfo_QueryClassesFromCreatorResponse.Size(m)
}
func (m *QueryClassesFromCreatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesFromCreatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesFromCreatorResponse proto.InternalMessageInfo

func (m *QueryClassesFromCreatorResponse) GetClassIds() []string {
	if m != nil {
		return m.ClassIds
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryClassAuthorityMetadataRequest)(nil), "retrochain.nftfactory.v1.QueryClassAuthorityMetadataRequest")
	proto.RegisterType((*QueryClassAuthorityMetadataResponse)(nil), "retrochain.nftfactory.v1.QueryClassAuthorityMetadataResponse")
	proto.RegisterType((*ClassAuthorityMetadata)(nil), "retrochain.nftfactory.v1.ClassAuthorityMetadata")
	proto.RegisterType((*QueryClassesFromCreatorRequest)(nil), "retrochain.nftfactory.v1.QueryClassesFromCreatorRequest")
	proto.RegisterType((*QueryClassesFromCreatorResponse)(nil), "retrochain.nftfactory.v1.QueryClassesFromCreatorResponse")
}

func init() {
	proto.RegisterFile("retrochain/nftfactory/v1/query.proto", fileDescriptor_69422d58e61ed49f)
}

var fileDescriptor_69422d58e61ed49f = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x4d, 0xbf, 0x4f, 0x04, 0xc6, 0x95, 0x13, 0x63, 0x2a, 0xfe, 0x40, 0xaa, 0x89, 0xb8, 0xb0,
	0x23, 0xb8, 0x41, 0xe3, 0x4f, 0x94, 0xc4, 0xc4, 0x85, 0x0b, 0x59, 0xb2, 0x69, 0xc6, 0x76, 0x80,
	0x46, 0x3a, 0x53, 0x66, 0x06, 0x62, 0x63, 0xdc, 0x98, 0xe8, 0x0b, 0xf8, 0x68, 0xbe, 0x82, 0x8f,
	0xc1, 0xc2, 0xd0, 0x0e, 0x42, 0x80, 0x11, 0xc3, 0xae, 0x77, 0xee, 0x3d, 0x27, 0xe7, 0x9c, 0x7b,
	0x0b, 0xf6, 0x38, 0x91, 0x9c, 0xb9, 0x2d, 0xec, 0x53, 0x44, 0x1b, 0xb2, 0x81, 0x5d, 0xc9, 0x78,
	0x84, 0x7a, 0x25, 0xd4, 0xe9, 0x12, 0x1e, 0xd9, 0x21, 0x67, 0x92, 0x41, 0x73, 0x34, 0x65, 0x8f,
	0xa6, 0xec, 0x5e, 0x29, 0xb7, 0xd5, 0x64, 0xac, 0xd9, 0x26, 0x08, 0x87, 0x3e, 0xc2, 0x94, 0x32,
	0x89, 0xa5, 0xcf, 0xa8, 0x48, 0x70, 0xd6, 0x25, 0xb0, 0xee, 0x07, 0x34, 0xd5, 0x36, 0x16, 0xe2,
	0xaa, 0x2b, 0x5b, 0x8c, 0xfb, 0x32, 0xba, 0x23, 0x12, 0x7b, 0x58, 0xe2, 0x1a, 0xe9, 0x74, 0x89,
	0x90, 0x70, 0x03, 0x64, 0xdc, 0xc1, 0x80, 0xe3, 0x7b, 0xa6, 0x51, 0x30, 0x8a, 0xd9, 0x5a, 0x3a,
	0xae, 0x6f, 0x3d, 0xeb, 0xdd, 0x00, 0xbb, 0xbf, 0x32, 0x88, 0x90, 0x51, 0x41, 0xa0, 0x03,
	0x20, 0x1e, 0x36, 0x9d, 0x40, 0x75, 0x63, 0xb2, 0x95, 0xf2, 0x91, 0xad, 0x53, 0x6f, 0x6b, 0x58,
	0x57, 0xf1, 0xe4, 0x93, 0x65, 0x83, 0xf5, 0xd9, 0xc3, 0x70, 0x0d, 0xa4, 0xb0, 0x17, 0xf8, 0x54,
	0x49, 0x4f, 0x0a, 0xeb, 0x14, 0xec, 0x8c, 0x74, 0x13, 0x71, 0xc3, 0x59, 0x50, 0xe5, 0x04, 0x4b,
	0xc6, 0x87, 0xae, 0x4d, 0x90, 0x76, 0x93, 0x97, 0x1f, 0xd3, 0x49, 0x69, 0x5d, 0x80, 0xbc, 0x16,
	0xab, 0xfc, 0x6e, 0x82, 0xec, 0x30, 0x32, 0x61, 0x1a, 0x85, 0xff, 0xc5, 0x6c, 0x2d, 0xa3, 0x32,
	0x13, 0xe5, 0xb7, 0x25, 0x90, 0x8a, 0x09, 0x60, 0xdf, 0xd0, 0xca, 0x3e, 0xd3, 0xa7, 0x32, 0x7f,
	0x65, 0xb9, 0xf3, 0x05, 0xd1, 0x89, 0x7c, 0x8b, 0xbc, 0x7e, 0x7e, 0x7d, 0xfc, 0x73, 0xea, 0x07,
	0x70, 0x7f, 0xe2, 0xea, 0x12, 0x57, 0xd3, 0xbb, 0x84, 0x65, 0xa4, 0xbd, 0x54, 0x2d, 0xa6, 0x6f,
	0x00, 0x38, 0x1d, 0x22, 0xac, 0xfc, 0x45, 0xfc, 0xac, 0x9d, 0xe5, 0x4e, 0x16, 0x40, 0x2a, 0xcb,
	0x9d, 0xd8, 0xf2, 0x63, 0x1d, 0xc1, 0xc3, 0x59, 0xf2, 0x89, 0x70, 0x1a, 0x9c, 0x05, 0x8e,
	0xba, 0x01, 0xf4, 0xac, 0x3e, 0x5e, 0x60, 0x65, 0x8e, 0x71, 0x2d, 0xf2, 0x3a, 0x5f, 0xdf, 0x1e,
	0x83, 0x3e, 0x8d, 0x83, 0x65, 0x14, 0x12, 0xf1, 0xb0, 0x1c, 0xff, 0xa5, 0xc7, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x29, 0xb8, 0x18, 0x64, 0x05, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	ClassAuthorityMetadata(ctx context.Context, in *QueryClassAuthorityMetadataRequest, opts ...grpc.CallOption) (*QueryClassAuthorityMetadataResponse, error)
	ClassesFromCreator(ctx context.Context, in *QueryClassesFromCreatorRequest, opts ...grpc.CallOption) (*QueryClassesFromCreatorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ClassAuthorityMetadata(ctx context.Context, in *QueryClassAuthorityMetadataRequest, opts ...grpc.CallOption) (*QueryClassAuthorityMetadataResponse, error) {
	out := new(QueryClassAuthorityMetadataResponse)
	err := c.cc.Invoke(ctx, "/retrochain.nftfactory.v1.Query/ClassAuthorityMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClassesFromCreator(ctx context.Context, in *QueryClassesFromCreatorRequest, opts ...grpc.CallOption) (*QueryClassesFromCreatorResponse, error) {
	out := new(QueryClassesFromCreatorResponse)
	err := c.cc.Invoke(ctx, "/retrochain.nftfactory.v1.Query/ClassesFromCreator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	ClassAuthorityMetadata(context.Context, *QueryClassAuthorityMetadataRequest) (*QueryClassAuthorityMetadataResponse, error)
	ClassesFromCreator(context.Context, *QueryClassesFromCreatorRequest) (*QueryClassesFromCreatorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ClassAuthorityMetadata(ctx context.Context, req *QueryClassAuthorityMetadataRequest) (*QueryClassAuthorityMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassAuthorityMetadata not implemented")
}
func (*UnimplementedQueryServer) ClassesFromCreator(ctx context.Context, req *QueryClassesFromCreatorRequest) (*QueryClassesFromCreatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassesFromCreator not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ClassAuthorityMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClassAuthorityMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassAuthorityMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.nftfactory.v1.Query/ClassAuthorityMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassAuthorityMetadata(ctx, req.(*QueryClassAuthorityMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClassesFromCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClassesFromCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassesFromCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.nftfactory.v1.Query/ClassesFromCreator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassesFromCreator(ctx, req.(*QueryClassesFromCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "retrochain.nftfactory.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassAuthorityMetadata",
			Handler:    _Query_ClassAuthorityMetadata_Handler,
		},
		{
			MethodName: "ClassesFromCreator",
			Handler:    _Query_ClassesFromCreator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrochain/nftfactory/v1/query.proto",
}
