// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/nftfactory/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateClass struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// sub_id is namespaced under the sender. ClassID will be:
	//
	//	nft/<sender>/<sub_id>
	SubId string `protobuf:"bytes,2,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	// Optional metadata fields forwarded to x/nft Class.
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Uri                  string   `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	UriHash              string   `protobuf:"bytes,7,opt,name=uri_hash,json=uriHash,proto3" json:"uri_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateClass) Reset()         { *m = MsgCreateClass{} }
func (m *MsgCreateClass) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClass) ProtoMessage()    {}
func (*MsgCreateClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ebb9448ee3919b, []int{0}
}
func (m *MsgCreateClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateClass.Unmarshal(m, b)
}
func (m *MsgCreateClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateClass.Marshal(b, m, deterministic)
}
func (m *MsgCreateClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClass.Merge(m, src)
}
func (m *MsgCreateClass) XXX_Size() int {
	return xxx_messageInfo_MsgCreateClass.Size(m)
}
func (m *MsgCreateClass) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClass.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClass proto.InternalMessageInfo

func (m *MsgCreateClass) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCreateClass) GetSubId() string {
	if m != nil {
		return m.SubId
	}
	return ""
}

func (m *MsgCreateClass) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateClass) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MsgCreateClass) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgCreateClass) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *MsgCreateClass) GetUriHash() string {
	if m != nil {
		return m.UriHash
	}
	return ""
}

type MsgCreateClassResponse struct {
	ClassId              string   `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateClassResponse) Reset()         { *m = MsgCreateClassResponse{} }
func (m *MsgCreateClassResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClassResponse) ProtoMessage()    {}
func (*MsgCreateClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ebb9448ee3919b, []int{1}
}
func (m *MsgCreateClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateClassResponse.Unmarshal(m, b)
}
func (m *MsgCreateClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateClassResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClassResponse.Merge(m, src)
}
func (m *MsgCreateClassResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateClassResponse.Size(m)
}
func (m *MsgCreateClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClassResponse proto.InternalMessageInfo

func (m *MsgCreateClassResponse) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

type MsgMint struct {
	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ClassId string `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Uri     string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	UriHash string `protobuf:"bytes,5,opt,name=uri_hash,json=uriHash,proto3" json:"uri_hash,omitempty"`
	// receiver defaults to sender when empty.
	Receiver             string   `protobuf:"bytes,6,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMint) Reset()         { *m = MsgMint{} }
func (m *MsgMint) String() string { return proto.CompactTextString(m) }
func (*MsgMint) ProtoMessage()    {}
func (*MsgMint) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ebb9448ee3919b, []int{2}
}
func (m *MsgMint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMint.Unmarshal(m, b)
}
func (m *MsgMint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMint.Marshal(b, m, deterministic)
}
func (m *MsgMint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMint.Merge(m, src)
}
func (m *MsgMint) XXX_Size() int {
	return xxx_messageInfo_MsgMint.Size(m)
}
func (m *MsgMint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMint proto.InternalMessageInfo

func (m *MsgMint) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgMint) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *MsgMint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgMint) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *MsgMint) GetUriHash() string {
	if m != nil {
		return m.UriHash
	}
	return ""
}

func (m *MsgMint) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

type MsgMintResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMintResponse) Reset()         { *m = MsgMintResponse{} }
func (m *MsgMintResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintResponse) ProtoMessage()    {}
func (*MsgMintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80ebb9448ee3919b, []int{3}
}
func (m *MsgMintResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMintResponse.Unmarshal(m, b)
}
func (m *MsgMintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMintResponse.Marshal(b, m, deterministic)
}
func (m *MsgMintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintResponse.Merge(m, src)
}
func (m *MsgMintResponse) XXX_Size() int {
	return xxx_messageInfo_MsgMintResponse.Size(m)
}
func (m *MsgMintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateClass)(nil), "retrochain.nftfactory.v1.MsgCreateClass")
	proto.RegisterType((*MsgCreateClassResponse)(nil), "retrochain.nftfactory.v1.MsgCreateClassResponse")
	proto.RegisterType((*MsgMint)(nil), "retrochain.nftfactory.v1.MsgMint")
	proto.RegisterType((*MsgMintResponse)(nil), "retrochain.nftfactory.v1.MsgMintResponse")
}

func init() { proto.RegisterFile("retrochain/nftfactory/v1/tx.proto", fileDescriptor_80ebb9448ee3919b) }

var fileDescriptor_80ebb9448ee3919b = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0x27, 0x71, 0xca, 0x54, 0x2a, 0x74, 0x05, 0x65, 0x6b, 0x09, 0xb5, 0xcd, 0x01,
	0x95, 0x48, 0xd8, 0x2d, 0x45, 0x1c, 0x7a, 0xa3, 0xbd, 0xd0, 0x43, 0x2e, 0x81, 0x13, 0x97, 0xc8,
	0xf1, 0x6e, 0x9d, 0x95, 0xea, 0xdd, 0x68, 0x67, 0x1d, 0x35, 0x37, 0xc4, 0x11, 0xf1, 0x30, 0x39,
	0xf0, 0x1a, 0x5c, 0x78, 0x89, 0xbc, 0x03, 0x27, 0xb4, 0x6b, 0xa7, 0xb5, 0x11, 0x09, 0x88, 0x4b,
	0x34, 0xf3, 0xcf, 0x3f, 0xb3, 0x3b, 0x5f, 0xd6, 0x70, 0xa4, 0xb9, 0xd1, 0x2a, 0x9d, 0x24, 0x42,
	0xc6, 0xf2, 0xda, 0x5c, 0x27, 0xa9, 0x51, 0x7a, 0x1e, 0xcf, 0x4e, 0x63, 0x73, 0x1b, 0x4d, 0xb5,
	0x32, 0x8a, 0xd0, 0x7b, 0x4b, 0x74, 0x6f, 0x89, 0x66, 0xa7, 0xe1, 0x6e, 0x92, 0x0b, 0xa9, 0x62,
	0xf7, 0x5b, 0x9a, 0xc3, 0xa7, 0xa9, 0xc2, 0x5c, 0x61, 0x9c, 0x63, 0x66, 0x87, 0xe4, 0x98, 0x55,
	0x85, 0xfd, 0xb2, 0x30, 0x72, 0x59, 0x5c, 0x26, 0x65, 0xa9, 0xf7, 0xd5, 0x87, 0x9d, 0x01, 0x66,
	0x97, 0x9a, 0x27, 0x86, 0x5f, 0xde, 0x24, 0x88, 0xe4, 0x04, 0x02, 0xe4, 0x92, 0x71, 0x4d, 0xbd,
	0x43, 0xef, 0xf8, 0xc1, 0x05, 0xfd, 0xf1, 0xed, 0xe5, 0xe3, 0xaa, 0xe9, 0x2d, 0x63, 0x9a, 0x23,
	0xbe, 0x37, 0x5a, 0xc8, 0x6c, 0x58, 0xf9, 0xc8, 0x13, 0x08, 0xb0, 0x18, 0x8f, 0x04, 0xa3, 0xbe,
	0xed, 0x18, 0x76, 0xb0, 0x18, 0x5f, 0x31, 0x42, 0xa0, 0x2d, 0x93, 0x9c, 0xd3, 0x96, 0x13, 0x5d,
	0x4c, 0xf6, 0x20, 0xc0, 0x79, 0x3e, 0x56, 0x37, 0xb4, 0xed, 0xd4, 0x2a, 0x23, 0x87, 0xb0, 0xcd,
	0x38, 0xa6, 0x5a, 0x4c, 0x8d, 0x50, 0x92, 0x76, 0x5c, 0xb1, 0x2e, 0x91, 0x47, 0xd0, 0x2a, 0xb4,
	0xa0, 0x81, 0xab, 0xd8, 0x90, 0xec, 0xc3, 0x56, 0xa1, 0xc5, 0x68, 0x92, 0xe0, 0x84, 0x76, 0x9d,
	0xdc, 0x2d, 0xb4, 0x78, 0x97, 0xe0, 0xe4, 0xfc, 0xcd, 0xe7, 0xe5, 0xa2, 0x5f, 0x5d, 0xef, 0xcb,
	0x72, 0xd1, 0x7f, 0x5e, 0x43, 0x7d, 0x5b, 0x87, 0xdd, 0xdc, 0xbd, 0x77, 0x06, 0x7b, 0x4d, 0x65,
	0xc8, 0x71, 0xaa, 0x24, 0x72, 0x7b, 0x58, 0x6a, 0x05, 0xbb, 0xa5, 0x57, 0x1e, 0xe6, 0xf2, 0x2b,
	0xd6, 0xfb, 0xe9, 0x41, 0x77, 0x80, 0xd9, 0x40, 0x48, 0xf3, 0x1f, 0xf0, 0xea, 0x83, 0xfd, 0xc6,
	0x60, 0xb2, 0x03, 0xbe, 0x60, 0x15, 0x3e, 0x5f, 0xb0, 0x15, 0x82, 0xf6, 0x9f, 0x11, 0x74, 0x1a,
	0x08, 0xc8, 0x6b, 0xd8, 0xd2, 0x3c, 0xe5, 0x62, 0xc6, 0x75, 0x09, 0x6d, 0xc3, 0x5d, 0xee, 0x9c,
	0xe7, 0xf1, 0x6f, 0xe0, 0x0e, 0x36, 0x80, 0xb3, 0x0b, 0xf7, 0x76, 0xe1, 0x61, 0x15, 0xae, 0x50,
	0xbd, 0xfa, 0xee, 0x41, 0x6b, 0x80, 0x19, 0x11, 0xb0, 0x5d, 0x7f, 0x57, 0xc7, 0xd1, 0xba, 0xc7,
	0x1c, 0x35, 0x99, 0x87, 0x27, 0xff, 0xea, 0xbc, 0xfb, 0x77, 0x3e, 0x40, 0xdb, 0xe1, 0x3f, 0xda,
	0xd8, 0x69, 0x2d, 0xe1, 0x8b, 0xbf, 0x5a, 0x56, 0x53, 0xc3, 0xce, 0xa7, 0xe5, 0xa2, 0xef, 0x5d,
	0x1c, 0x7c, 0x7c, 0xb6, 0x8e, 0x82, 0x99, 0x4f, 0x39, 0x8e, 0x03, 0xf7, 0x2d, 0x9d, 0xfd, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0x38, 0xce, 0x60, 0xd1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateClass(ctx context.Context, in *MsgCreateClass, opts ...grpc.CallOption) (*MsgCreateClassResponse, error)
	Mint(ctx context.Context, in *MsgMint, opts ...grpc.CallOption) (*MsgMintResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateClass(ctx context.Context, in *MsgCreateClass, opts ...grpc.CallOption) (*MsgCreateClassResponse, error) {
	out := new(MsgCreateClassResponse)
	err := c.cc.Invoke(ctx, "/retrochain.nftfactory.v1.Msg/CreateClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Mint(ctx context.Context, in *MsgMint, opts ...grpc.CallOption) (*MsgMintResponse, error) {
	out := new(MsgMintResponse)
	err := c.cc.Invoke(ctx, "/retrochain.nftfactory.v1.Msg/Mint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateClass(context.Context, *MsgCreateClass) (*MsgCreateClassResponse, error)
	Mint(context.Context, *MsgMint) (*MsgMintResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateClass(ctx context.Context, req *MsgCreateClass) (*MsgCreateClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClass not implemented")
}
func (*UnimplementedMsgServer) Mint(ctx context.Context, req *MsgMint) (*MsgMintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mint not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateClass)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.nftfactory.v1.Msg/CreateClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateClass(ctx, req.(*MsgCreateClass))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Mint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Mint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.nftfactory.v1.Msg/Mint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Mint(ctx, req.(*MsgMint))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "retrochain.nftfactory.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClass",
			Handler:    _Msg_CreateClass_Handler,
		},
		{
			MethodName: "Mint",
			Handler:    _Msg_Mint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrochain/nftfactory/v1/tx.proto",
}
