// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/arcade/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Base credits cost per game (in uretro)
	BaseCreditsCost uint64 `protobuf:"varint,1,opt,name=base_credits_cost,json=baseCreditsCost,proto3" json:"base_credits_cost,omitempty"`
	// Tokens earned per 1000 points scored
	TokensPerThousandPoints uint32 `protobuf:"varint,2,opt,name=tokens_per_thousand_points,json=tokensPerThousandPoints,proto3" json:"tokens_per_thousand_points,omitempty"`
	// Maximum active sessions per player
	MaxActiveSessions uint32 `protobuf:"varint,3,opt,name=max_active_sessions,json=maxActiveSessions,proto3" json:"max_active_sessions,omitempty"`
	// Continue cost multiplier (percentage)
	ContinueCostMultiplier uint32 `protobuf:"varint,4,opt,name=continue_cost_multiplier,json=continueCostMultiplier,proto3" json:"continue_cost_multiplier,omitempty"`
	// High score reward in arcade tokens
	HighScoreReward uint32 `protobuf:"varint,5,opt,name=high_score_reward,json=highScoreReward,proto3" json:"high_score_reward,omitempty"`
	// Tournament registration fee (in uretro)
	TournamentRegistrationFee uint64 `protobuf:"varint,6,opt,name=tournament_registration_fee,json=tournamentRegistrationFee,proto3" json:"tournament_registration_fee,omitempty"`
	// Minimum game difficulty (1-10)
	MinDifficulty uint32 `protobuf:"varint,7,opt,name=min_difficulty,json=minDifficulty,proto3" json:"min_difficulty,omitempty"`
	// Maximum game difficulty (1-10)
	MaxDifficulty uint32 `protobuf:"varint,8,opt,name=max_difficulty,json=maxDifficulty,proto3" json:"max_difficulty,omitempty"`
	// Achievement reward multiplier
	AchievementRewardMultiplier uint32 `protobuf:"varint,9,opt,name=achievement_reward_multiplier,json=achievementRewardMultiplier,proto3" json:"achievement_reward_multiplier,omitempty"`
	// Power-up cost in arcade tokens
	PowerUpCost uint32 `protobuf:"varint,10,opt,name=power_up_cost,json=powerUpCost,proto3" json:"power_up_cost,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da93c7a0d422d3b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaseCreditsCost() uint64 {
	if m != nil {
		return m.BaseCreditsCost
	}
	return 0
}

func (m *Params) GetTokensPerThousandPoints() uint32 {
	if m != nil {
		return m.TokensPerThousandPoints
	}
	return 0
}

func (m *Params) GetMaxActiveSessions() uint32 {
	if m != nil {
		return m.MaxActiveSessions
	}
	return 0
}

func (m *Params) GetContinueCostMultiplier() uint32 {
	if m != nil {
		return m.ContinueCostMultiplier
	}
	return 0
}

func (m *Params) GetHighScoreReward() uint32 {
	if m != nil {
		return m.HighScoreReward
	}
	return 0
}

func (m *Params) GetTournamentRegistrationFee() uint64 {
	if m != nil {
		return m.TournamentRegistrationFee
	}
	return 0
}

func (m *Params) GetMinDifficulty() uint32 {
	if m != nil {
		return m.MinDifficulty
	}
	return 0
}

func (m *Params) GetMaxDifficulty() uint32 {
	if m != nil {
		return m.MaxDifficulty
	}
	return 0
}

func (m *Params) GetAchievementRewardMultiplier() uint32 {
	if m != nil {
		return m.AchievementRewardMultiplier
	}
	return 0
}

func (m *Params) GetPowerUpCost() uint32 {
	if m != nil {
		return m.PowerUpCost
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "retrochain.arcade.v1.Params")
}

func init() { proto.RegisterFile("retrochain/arcade/v1/params.proto", fileDescriptor_6da93c7a0d422d3b) }

var fileDescriptor_6da93c7a0d422d3b = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x63, 0x08, 0x01, 0x16, 0x85, 0x2a, 0xa6, 0x02, 0x37, 0x15, 0xa6, 0x14, 0x21, 0x55,
	0x3d, 0xc4, 0xaa, 0x7a, 0x41, 0x20, 0x21, 0xd1, 0x22, 0x6e, 0x48, 0x51, 0x0a, 0x17, 0x2e, 0xab,
	0xad, 0x3d, 0x89, 0x57, 0xc4, 0x3b, 0xab, 0xdd, 0x71, 0xea, 0xbe, 0x02, 0x27, 0x1e, 0x01, 0xf1,
	0x04, 0x3c, 0x06, 0xc7, 0x1e, 0x39, 0xa2, 0xe4, 0x00, 0x8f, 0x81, 0x3c, 0x4e, 0x5b, 0x1f, 0xb8,
	0x58, 0xab, 0xff, 0xff, 0x7e, 0x7b, 0x66, 0xfd, 0x8b, 0xa7, 0x0e, 0xc8, 0x61, 0x9a, 0x2b, 0x6d,
	0x12, 0xe5, 0x52, 0x95, 0x41, 0xb2, 0x38, 0x48, 0xac, 0x72, 0xaa, 0xf0, 0x23, 0xeb, 0x90, 0x30,
	0xdc, 0xbc, 0x46, 0x46, 0x0d, 0x32, 0x5a, 0x1c, 0x0c, 0x07, 0xaa, 0xd0, 0x06, 0x13, 0x7e, 0x36,
	0xe0, 0x70, 0x73, 0x86, 0x33, 0xe4, 0x63, 0x52, 0x9f, 0x1a, 0x75, 0xf7, 0x7b, 0x57, 0xf4, 0xc6,
	0xfc, 0xbe, 0x70, 0x5f, 0x0c, 0x4e, 0x95, 0x07, 0x99, 0x3a, 0xc8, 0x34, 0x79, 0x99, 0xa2, 0xa7,
	0x28, 0xd8, 0x09, 0xf6, 0xba, 0x93, 0x8d, 0xda, 0x38, 0x6e, 0xf4, 0x63, 0xf4, 0x14, 0xbe, 0x12,
	0x43, 0xc2, 0xcf, 0x60, 0xbc, 0xb4, 0xe0, 0x24, 0xe5, 0x58, 0x7a, 0x65, 0x32, 0x69, 0x51, 0x1b,
	0xf2, 0xd1, 0x8d, 0x9d, 0x60, 0xaf, 0x3f, 0x79, 0xd4, 0x10, 0x63, 0x70, 0x1f, 0xd6, 0xfe, 0x98,
	0xed, 0x70, 0x24, 0x1e, 0x14, 0xaa, 0x92, 0x2a, 0x25, 0xbd, 0x00, 0xe9, 0xc1, 0x7b, 0x8d, 0xc6,
	0x47, 0x37, 0x39, 0x35, 0x28, 0x54, 0xf5, 0x86, 0x9d, 0x93, 0xb5, 0x11, 0xbe, 0x10, 0x51, 0x8a,
	0x86, 0xb4, 0x29, 0x81, 0x87, 0x92, 0x45, 0x39, 0x27, 0x6d, 0xe7, 0x1a, 0x5c, 0xd4, 0xe5, 0xd0,
	0xc3, 0x4b, 0xbf, 0x1e, 0xee, 0xfd, 0x95, 0x5b, 0xaf, 0x94, 0xeb, 0x59, 0x2e, 0x7d, 0x8a, 0x0e,
	0xa4, 0x83, 0x33, 0xe5, 0xb2, 0xe8, 0x16, 0x47, 0x36, 0x6a, 0xe3, 0xa4, 0xd6, 0x27, 0x2c, 0x87,
	0xaf, 0xc5, 0x36, 0x61, 0xe9, 0x8c, 0x2a, 0xc0, 0x90, 0x74, 0x30, 0xd3, 0x9e, 0x9c, 0x22, 0x8d,
	0x46, 0x4e, 0x01, 0xa2, 0x1e, 0x5f, 0xc4, 0xd6, 0x35, 0x32, 0x69, 0x11, 0xef, 0x00, 0xc2, 0xe7,
	0xe2, 0x7e, 0xa1, 0x8d, 0xcc, 0xf4, 0x74, 0xaa, 0xd3, 0x72, 0x4e, 0xe7, 0xd1, 0x6d, 0xfe, 0x50,
	0xbf, 0xd0, 0xe6, 0xed, 0x95, 0xc8, 0x98, 0xaa, 0xda, 0xd8, 0x9d, 0x35, 0xa6, 0xaa, 0x16, 0x76,
	0x24, 0x1e, 0xab, 0x34, 0xd7, 0xb0, 0x80, 0xf5, 0x38, 0xf5, 0x8c, 0xed, 0xc5, 0xef, 0x72, 0x6a,
	0xbb, 0x05, 0x35, 0x7b, 0xb4, 0xb6, 0xdf, 0x15, 0x7d, 0x8b, 0x67, 0xe0, 0x64, 0x69, 0x9b, 0x9f,
	0x29, 0x38, 0x73, 0x8f, 0xc5, 0x8f, 0xb6, 0xbe, 0xab, 0x97, 0xcf, 0xfe, 0x7e, 0x7b, 0x12, 0x7c,
	0xf9, 0xf3, 0x63, 0x7f, 0xd8, 0xaa, 0x5a, 0x75, 0x59, 0xb6, 0xa6, 0x19, 0x47, 0x87, 0x3f, 0x97,
	0x71, 0x70, 0xb1, 0x8c, 0x83, 0xdf, 0xcb, 0x38, 0xf8, 0xba, 0x8a, 0x3b, 0x17, 0xab, 0xb8, 0xf3,
	0x6b, 0x15, 0x77, 0x3e, 0x6d, 0xfd, 0x2f, 0x45, 0xe7, 0x16, 0xfc, 0x69, 0x8f, 0x0b, 0x76, 0xf8,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xe4, 0x5d, 0xbd, 0xc4, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BaseCreditsCost != that1.BaseCreditsCost {
		return false
	}
	if this.TokensPerThousandPoints != that1.TokensPerThousandPoints {
		return false
	}
	if this.MaxActiveSessions != that1.MaxActiveSessions {
		return false
	}
	if this.ContinueCostMultiplier != that1.ContinueCostMultiplier {
		return false
	}
	if this.HighScoreReward != that1.HighScoreReward {
		return false
	}
	if this.TournamentRegistrationFee != that1.TournamentRegistrationFee {
		return false
	}
	if this.MinDifficulty != that1.MinDifficulty {
		return false
	}
	if this.MaxDifficulty != that1.MaxDifficulty {
		return false
	}
	if this.AchievementRewardMultiplier != that1.AchievementRewardMultiplier {
		return false
	}
	if this.PowerUpCost != that1.PowerUpCost {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PowerUpCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PowerUpCost))
		i--
		dAtA[i] = 0x50
	}
	if m.AchievementRewardMultiplier != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AchievementRewardMultiplier))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxDifficulty != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDifficulty))
		i--
		dAtA[i] = 0x40
	}
	if m.MinDifficulty != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDifficulty))
		i--
		dAtA[i] = 0x38
	}
	if m.TournamentRegistrationFee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TournamentRegistrationFee))
		i--
		dAtA[i] = 0x30
	}
	if m.HighScoreReward != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HighScoreReward))
		i--
		dAtA[i] = 0x28
	}
	if m.ContinueCostMultiplier != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ContinueCostMultiplier))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxActiveSessions != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxActiveSessions))
		i--
		dAtA[i] = 0x18
	}
	if m.TokensPerThousandPoints != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TokensPerThousandPoints))
		i--
		dAtA[i] = 0x10
	}
	if m.BaseCreditsCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BaseCreditsCost))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseCreditsCost != 0 {
		n += 1 + sovParams(uint64(m.BaseCreditsCost))
	}
	if m.TokensPerThousandPoints != 0 {
		n += 1 + sovParams(uint64(m.TokensPerThousandPoints))
	}
	if m.MaxActiveSessions != 0 {
		n += 1 + sovParams(uint64(m.MaxActiveSessions))
	}
	if m.ContinueCostMultiplier != 0 {
		n += 1 + sovParams(uint64(m.ContinueCostMultiplier))
	}
	if m.HighScoreReward != 0 {
		n += 1 + sovParams(uint64(m.HighScoreReward))
	}
	if m.TournamentRegistrationFee != 0 {
		n += 1 + sovParams(uint64(m.TournamentRegistrationFee))
	}
	if m.MinDifficulty != 0 {
		n += 1 + sovParams(uint64(m.MinDifficulty))
	}
	if m.MaxDifficulty != 0 {
		n += 1 + sovParams(uint64(m.MaxDifficulty))
	}
	if m.AchievementRewardMultiplier != 0 {
		n += 1 + sovParams(uint64(m.AchievementRewardMultiplier))
	}
	if m.PowerUpCost != 0 {
		n += 1 + sovParams(uint64(m.PowerUpCost))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseCreditsCost", wireType)
			}
			m.BaseCreditsCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseCreditsCost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokensPerThousandPoints", wireType)
			}
			m.TokensPerThousandPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokensPerThousandPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxActiveSessions", wireType)
			}
			m.MaxActiveSessions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxActiveSessions |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContinueCostMultiplier", wireType)
			}
			m.ContinueCostMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContinueCostMultiplier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighScoreReward", wireType)
			}
			m.HighScoreReward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HighScoreReward |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TournamentRegistrationFee", wireType)
			}
			m.TournamentRegistrationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TournamentRegistrationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDifficulty", wireType)
			}
			m.MinDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDifficulty |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDifficulty", wireType)
			}
			m.MaxDifficulty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDifficulty |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AchievementRewardMultiplier", wireType)
			}
			m.AchievementRewardMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AchievementRewardMultiplier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerUpCost", wireType)
			}
			m.PowerUpCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PowerUpCost |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
