// Code generated by hand for lightweight params handling (no proto schema).
// This module keeps params simple and uses JSON encoding via codec.
// Fields match types.Params.

package types

import math "cosmossdk.io/math"

// Ensure Params implements the sdk params interface expectations in module wiring.
func (p *Params) UnpackInterfaces(_ interface{}) error { return nil }

// Copy returns a shallow copy.
func (p Params) Copy() Params {
	return Params{FeeBurnRate: p.FeeBurnRate, ProvisionBurnRate: p.ProvisionBurnRate}
}

// Zero returns a zeroed params.
func ZeroParams() Params {
	return Params{FeeBurnRate: math.LegacyZeroDec(), ProvisionBurnRate: math.LegacyZeroDec()}
}
