// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/retrochain/arcade/v1/tx";
import { MsgInsertCoin } from "./types/retrochain/arcade/v1/tx";
import { MsgSubmitScore } from "./types/retrochain/arcade/v1/tx";
import { MsgStartSession } from "./types/retrochain/arcade/v1/tx";

import { Params as typeParams} from "./types"

export { MsgUpdateParams, MsgInsertCoin, MsgSubmitScore, MsgStartSession };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgInsertCoinParams = {
  value: MsgInsertCoin,
  fee?: StdFee,
  memo?: string
};

type sendMsgSubmitScoreParams = {
  value: MsgSubmitScore,
  fee?: StdFee,
  memo?: string
};

type sendMsgStartSessionParams = {
  value: MsgStartSession,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgInsertCoinParams = {
  value: MsgInsertCoin,
};

type msgSubmitScoreParams = {
  value: MsgSubmitScore,
};

type msgStartSessionParams = {
  value: MsgStartSession,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgInsertCoin({ value, fee, memo }: sendMsgInsertCoinParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgInsertCoin: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgInsertCoin({ value: MsgInsertCoin.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgInsertCoin: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSubmitScore({ value, fee, memo }: sendMsgSubmitScoreParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSubmitScore: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSubmitScore({ value: MsgSubmitScore.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSubmitScore: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStartSession({ value, fee, memo }: sendMsgStartSessionParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStartSession: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgStartSession({ value: MsgStartSession.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStartSession: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/retrochain.arcade.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgInsertCoin({ value }: msgInsertCoinParams): EncodeObject {
			try {
				return { typeUrl: "/retrochain.arcade.v1.MsgInsertCoin", value: MsgInsertCoin.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgInsertCoin: Could not create message: ' + e.message)
			}
		},
		
		msgSubmitScore({ value }: msgSubmitScoreParams): EncodeObject {
			try {
				return { typeUrl: "/retrochain.arcade.v1.MsgSubmitScore", value: MsgSubmitScore.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSubmitScore: Could not create message: ' + e.message)
			}
		},
		
		msgStartSession({ value }: msgStartSessionParams): EncodeObject {
			try {
				return { typeUrl: "/retrochain.arcade.v1.MsgStartSession", value: MsgStartSession.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStartSession: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			RetrochainArcadeV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;