// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/tokenfactory/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	DenomAuthorities     []DenomAuthority `protobuf:"bytes,1,rep,name=denom_authorities,json=denomAuthorities,proto3" json:"denom_authorities"`
	CreatorDenoms        []CreatorDenom   `protobuf:"bytes,2,rep,name=creator_denoms,json=creatorDenoms,proto3" json:"creator_denoms"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_030cf1b57fe77ed3, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetDenomAuthorities() []DenomAuthority {
	if m != nil {
		return m.DenomAuthorities
	}
	return nil
}

func (m *GenesisState) GetCreatorDenoms() []CreatorDenom {
	if m != nil {
		return m.CreatorDenoms
	}
	return nil
}

type DenomAuthority struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Admin                string   `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenomAuthority) Reset()         { *m = DenomAuthority{} }
func (m *DenomAuthority) String() string { return proto.CompactTextString(m) }
func (*DenomAuthority) ProtoMessage()    {}
func (*DenomAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_030cf1b57fe77ed3, []int{1}
}
func (m *DenomAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenomAuthority.Unmarshal(m, b)
}
func (m *DenomAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenomAuthority.Marshal(b, m, deterministic)
}
func (m *DenomAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomAuthority.Merge(m, src)
}
func (m *DenomAuthority) XXX_Size() int {
	return xxx_messageInfo_DenomAuthority.Size(m)
}
func (m *DenomAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_DenomAuthority proto.InternalMessageInfo

func (m *DenomAuthority) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomAuthority) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

type CreatorDenom struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatorDenom) Reset()         { *m = CreatorDenom{} }
func (m *CreatorDenom) String() string { return proto.CompactTextString(m) }
func (*CreatorDenom) ProtoMessage()    {}
func (*CreatorDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_030cf1b57fe77ed3, []int{2}
}
func (m *CreatorDenom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatorDenom.Unmarshal(m, b)
}
func (m *CreatorDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatorDenom.Marshal(b, m, deterministic)
}
func (m *CreatorDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatorDenom.Merge(m, src)
}
func (m *CreatorDenom) XXX_Size() int {
	return xxx_messageInfo_CreatorDenom.Size(m)
}
func (m *CreatorDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatorDenom.DiscardUnknown(m)
}

var xxx_messageInfo_CreatorDenom proto.InternalMessageInfo

func (m *CreatorDenom) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CreatorDenom) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "retrochain.tokenfactory.v1.GenesisState")
	proto.RegisterType((*DenomAuthority)(nil), "retrochain.tokenfactory.v1.DenomAuthority")
	proto.RegisterType((*CreatorDenom)(nil), "retrochain.tokenfactory.v1.CreatorDenom")
}

func init() {
	proto.RegisterFile("retrochain/tokenfactory/v1/genesis.proto", fileDescriptor_030cf1b57fe77ed3)
}

var fileDescriptor_030cf1b57fe77ed3 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xed, 0x74, 0x8a, 0x71, 0x0e, 0x0d, 0xbd, 0xa8, 0xbd, 0xd9, 0xec, 0x55, 0x11, 0x4c,
	0xd9, 0x7c, 0x82, 0x55, 0xc1, 0xfb, 0x0e, 0x45, 0x04, 0x29, 0xb1, 0x8d, 0x5d, 0x90, 0xe6, 0x8c,
	0x24, 0x0e, 0xfb, 0x5e, 0x3e, 0x82, 0x17, 0x5e, 0xfb, 0x00, 0x3e, 0x8b, 0x34, 0xa9, 0x2c, 0xbb,
	0x70, 0x77, 0x3d, 0x7f, 0xff, 0xff, 0xfb, 0x0f, 0x39, 0x28, 0x96, 0x4c, 0x4b, 0x28, 0x16, 0x94,
	0x8b, 0x44, 0xc3, 0x2b, 0x13, 0x2f, 0xb4, 0xd0, 0x20, 0x9b, 0x64, 0x35, 0x49, 0x2a, 0x26, 0x98,
	0xe2, 0x8a, 0x2c, 0x25, 0x68, 0xc0, 0xe1, 0xda, 0x49, 0x5c, 0x27, 0x59, 0x4d, 0xc2, 0xb3, 0x02,
	0x54, 0x0d, 0x2a, 0x37, 0xce, 0xc4, 0x0e, 0x36, 0x16, 0xfa, 0x15, 0x54, 0x60, 0xf5, 0xf6, 0xcb,
	0xaa, 0xd1, 0xa7, 0x87, 0x06, 0xb7, 0x16, 0x3f, 0xd7, 0x54, 0x33, 0xfc, 0x84, 0x4e, 0x4b, 0x26,
	0xa0, 0xce, 0xe9, 0x9b, 0x5e, 0x80, 0xe4, 0x9a, 0x33, 0x15, 0x78, 0xe3, 0xdd, 0xf8, 0x68, 0x7a,
	0x41, 0xfe, 0x6f, 0x26, 0x37, 0x6d, 0x68, 0xd6, 0x65, 0x9a, 0x74, 0xef, 0xeb, 0x67, 0xb4, 0x93,
	0x9d, 0x94, 0xae, 0xca, 0x99, 0xc2, 0x77, 0x68, 0x58, 0x48, 0x46, 0x35, 0xc8, 0xdc, 0xfc, 0x53,
	0x41, 0xcf, 0xb0, 0xe3, 0x6d, 0xec, 0x6b, 0x9b, 0x30, 0x15, 0x1d, 0xf9, 0xb8, 0x70, 0x34, 0x15,
	0xdd, 0xa3, 0xe1, 0xe6, 0x02, 0xd8, 0x47, 0x7d, 0x53, 0x10, 0x78, 0x63, 0x2f, 0x3e, 0xcc, 0xec,
	0x80, 0x09, 0xea, 0xd3, 0xb2, 0xe6, 0x22, 0xe8, 0xb5, 0x6a, 0x1a, 0x7c, 0x7f, 0x5c, 0xfa, 0xdd,
	0x2b, 0xcd, 0xca, 0x52, 0x32, 0xa5, 0xe6, 0x5a, 0x72, 0x51, 0x65, 0xd6, 0x16, 0x3d, 0xa0, 0x81,
	0x5b, 0x8e, 0xa7, 0xe8, 0xa0, 0x2b, 0xb6, 0xdc, 0x2d, 0x84, 0x3f, 0xe3, 0x7a, 0x93, 0x9e, 0xb3,
	0x49, 0x7a, 0xfe, 0x38, 0x72, 0x2e, 0xfe, 0xbe, 0x79, 0x73, 0xdd, 0x2c, 0x99, 0x7a, 0xde, 0x37,
	0x27, 0xba, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x27, 0x10, 0x13, 0x0f, 0x1b, 0x02, 0x00, 0x00,
}
