// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/tokenfactory/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryDenomAuthorityMetadataRequest struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDenomAuthorityMetadataRequest) Reset()         { *m = QueryDenomAuthorityMetadataRequest{} }
func (m *QueryDenomAuthorityMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDenomAuthorityMetadataRequest) ProtoMessage()    {}
func (*QueryDenomAuthorityMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d51229c18b4868, []int{0}
}
func (m *QueryDenomAuthorityMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomAuthorityMetadataRequest.Unmarshal(m, b)
}
func (m *QueryDenomAuthorityMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomAuthorityMetadataRequest.Marshal(b, m, deterministic)
}
func (m *QueryDenomAuthorityMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomAuthorityMetadataRequest.Merge(m, src)
}
func (m *QueryDenomAuthorityMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDenomAuthorityMetadataRequest.Size(m)
}
func (m *QueryDenomAuthorityMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomAuthorityMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomAuthorityMetadataRequest proto.InternalMessageInfo

func (m *QueryDenomAuthorityMetadataRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryDenomAuthorityMetadataResponse struct {
	AuthorityMetadata    *DenomAuthorityMetadata `protobuf:"bytes,1,opt,name=authority_metadata,json=authorityMetadata,proto3" json:"authority_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QueryDenomAuthorityMetadataResponse) Reset()         { *m = QueryDenomAuthorityMetadataResponse{} }
func (m *QueryDenomAuthorityMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDenomAuthorityMetadataResponse) ProtoMessage()    {}
func (*QueryDenomAuthorityMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d51229c18b4868, []int{1}
}
func (m *QueryDenomAuthorityMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomAuthorityMetadataResponse.Unmarshal(m, b)
}
func (m *QueryDenomAuthorityMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomAuthorityMetadataResponse.Marshal(b, m, deterministic)
}
func (m *QueryDenomAuthorityMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomAuthorityMetadataResponse.Merge(m, src)
}
func (m *QueryDenomAuthorityMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDenomAuthorityMetadataResponse.Size(m)
}
func (m *QueryDenomAuthorityMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomAuthorityMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomAuthorityMetadataResponse proto.InternalMessageInfo

func (m *QueryDenomAuthorityMetadataResponse) GetAuthorityMetadata() *DenomAuthorityMetadata {
	if m != nil {
		return m.AuthorityMetadata
	}
	return nil
}

type DenomAuthorityMetadata struct {
	Admin                string   `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DenomAuthorityMetadata) Reset()         { *m = DenomAuthorityMetadata{} }
func (m *DenomAuthorityMetadata) String() string { return proto.CompactTextString(m) }
func (*DenomAuthorityMetadata) ProtoMessage()    {}
func (*DenomAuthorityMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d51229c18b4868, []int{2}
}
func (m *DenomAuthorityMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DenomAuthorityMetadata.Unmarshal(m, b)
}
func (m *DenomAuthorityMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DenomAuthorityMetadata.Marshal(b, m, deterministic)
}
func (m *DenomAuthorityMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomAuthorityMetadata.Merge(m, src)
}
func (m *DenomAuthorityMetadata) XXX_Size() int {
	return xxx_messageInfo_DenomAuthorityMetadata.Size(m)
}
func (m *DenomAuthorityMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomAuthorityMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DenomAuthorityMetadata proto.InternalMessageInfo

func (m *DenomAuthorityMetadata) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

type QueryDenomsFromCreatorRequest struct {
	Creator              string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDenomsFromCreatorRequest) Reset()         { *m = QueryDenomsFromCreatorRequest{} }
func (m *QueryDenomsFromCreatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDenomsFromCreatorRequest) ProtoMessage()    {}
func (*QueryDenomsFromCreatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d51229c18b4868, []int{3}
}
func (m *QueryDenomsFromCreatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomsFromCreatorRequest.Unmarshal(m, b)
}
func (m *QueryDenomsFromCreatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomsFromCreatorRequest.Marshal(b, m, deterministic)
}
func (m *QueryDenomsFromCreatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomsFromCreatorRequest.Merge(m, src)
}
func (m *QueryDenomsFromCreatorRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDenomsFromCreatorRequest.Size(m)
}
func (m *QueryDenomsFromCreatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomsFromCreatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomsFromCreatorRequest proto.InternalMessageInfo

func (m *QueryDenomsFromCreatorRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryDenomsFromCreatorResponse struct {
	Denoms               []string `protobuf:"bytes,1,rep,name=denoms,proto3" json:"denoms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDenomsFromCreatorResponse) Reset()         { *m = QueryDenomsFromCreatorResponse{} }
func (m *QueryDenomsFromCreatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDenomsFromCreatorResponse) ProtoMessage()    {}
func (*QueryDenomsFromCreatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4d51229c18b4868, []int{4}
}
func (m *QueryDenomsFromCreatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDenomsFromCreatorResponse.Unmarshal(m, b)
}
func (m *QueryDenomsFromCreatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDenomsFromCreatorResponse.Marshal(b, m, deterministic)
}
func (m *QueryDenomsFromCreatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDenomsFromCreatorResponse.Merge(m, src)
}
func (m *QueryDenomsFromCreatorResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDenomsFromCreatorResponse.Size(m)
}
func (m *QueryDenomsFromCreatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDenomsFromCreatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDenomsFromCreatorResponse proto.InternalMessageInfo

func (m *QueryDenomsFromCreatorResponse) GetDenoms() []string {
	if m != nil {
		return m.Denoms
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryDenomAuthorityMetadataRequest)(nil), "retrochain.tokenfactory.v1.QueryDenomAuthorityMetadataRequest")
	proto.RegisterType((*QueryDenomAuthorityMetadataResponse)(nil), "retrochain.tokenfactory.v1.QueryDenomAuthorityMetadataResponse")
	proto.RegisterType((*DenomAuthorityMetadata)(nil), "retrochain.tokenfactory.v1.DenomAuthorityMetadata")
	proto.RegisterType((*QueryDenomsFromCreatorRequest)(nil), "retrochain.tokenfactory.v1.QueryDenomsFromCreatorRequest")
	proto.RegisterType((*QueryDenomsFromCreatorResponse)(nil), "retrochain.tokenfactory.v1.QueryDenomsFromCreatorResponse")
}

func init() {
	proto.RegisterFile("retrochain/tokenfactory/v1/query.proto", fileDescriptor_a4d51229c18b4868)
}

var fileDescriptor_a4d51229c18b4868 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0x53, 0x9e, 0x07, 0x0c, 0xeb, 0x89, 0x8d, 0x21, 0xa4, 0xf1, 0x05, 0x6b, 0x62, 0x30,
	0x26, 0xad, 0xa0, 0x07, 0xe1, 0xa0, 0xf1, 0x25, 0xde, 0x3c, 0xc8, 0x91, 0x4b, 0xb3, 0x96, 0x05,
	0x1a, 0xed, 0x4e, 0xd9, 0x5d, 0x88, 0x8d, 0xf1, 0x62, 0x3c, 0x78, 0x34, 0xf1, 0xa3, 0xf9, 0x15,
	0xfc, 0x1e, 0x1a, 0xb6, 0xdb, 0x80, 0x42, 0xc1, 0x70, 0xeb, 0xec, 0xcc, 0x6f, 0xf2, 0xff, 0xcf,
	0x4c, 0xd1, 0x2e, 0xa7, 0x92, 0x83, 0xd7, 0x23, 0x3e, 0x73, 0x24, 0xdc, 0x51, 0xd6, 0x21, 0x9e,
	0x04, 0x1e, 0x39, 0xc3, 0xaa, 0xd3, 0x1f, 0x50, 0x1e, 0xd9, 0x21, 0x07, 0x09, 0xd8, 0x1c, 0xd7,
	0xd9, 0x93, 0x75, 0xf6, 0xb0, 0x6a, 0xae, 0x77, 0x01, 0xba, 0xf7, 0xd4, 0x21, 0xa1, 0xef, 0x10,
	0xc6, 0x40, 0x12, 0xe9, 0x03, 0x13, 0x31, 0x69, 0x35, 0x90, 0x75, 0x33, 0x6a, 0x74, 0x49, 0x19,
	0x04, 0x67, 0x03, 0xd9, 0x03, 0xee, 0xcb, 0xe8, 0x9a, 0x4a, 0xd2, 0x26, 0x92, 0x34, 0x69, 0x7f,
	0x40, 0x85, 0xc4, 0x6b, 0x28, 0xdb, 0x1e, 0x15, 0x94, 0x8c, 0xb2, 0x51, 0xc9, 0x37, 0xe3, 0xc0,
	0x7a, 0x35, 0xd0, 0xce, 0x5c, 0x58, 0x84, 0xc0, 0x04, 0xc5, 0x04, 0x61, 0x92, 0x24, 0xdd, 0x40,
	0x67, 0x55, 0xab, 0xd5, 0x5a, 0xcd, 0x4e, 0x97, 0x6e, 0xa7, 0xf4, 0x2d, 0x90, 0xdf, 0x4f, 0x96,
	0x8d, 0x8a, 0xb3, 0x8b, 0x47, 0xd2, 0x49, 0x3b, 0xf0, 0x59, 0x22, 0x5d, 0x05, 0x56, 0x1d, 0x6d,
	0x8c, 0x95, 0x8b, 0x2b, 0x0e, 0xc1, 0x05, 0xa7, 0x44, 0x02, 0x4f, 0x1c, 0x97, 0xd0, 0x8a, 0x17,
	0xbf, 0x68, 0x30, 0x09, 0xad, 0x63, 0xb4, 0x99, 0x86, 0x6a, 0xbf, 0x45, 0x94, 0x53, 0x03, 0x12,
	0x25, 0xa3, 0xfc, 0xaf, 0x92, 0x6f, 0xea, 0xa8, 0xf6, 0xf6, 0x1f, 0x65, 0x15, 0x8a, 0x5f, 0x32,
	0xa9, 0x7a, 0x4f, 0xe6, 0x0d, 0x64, 0xf1, 0xaa, 0xcc, 0xd3, 0xa5, 0xf9, 0x58, 0xbd, 0xe5, 0x3f,
	0x7f, 0x7c, 0xbe, 0x67, 0xbc, 0xd6, 0x3e, 0xde, 0x9b, 0xba, 0x39, 0x65, 0xc4, 0x9d, 0x5e, 0x26,
	0x3e, 0x72, 0xe6, 0x5c, 0x6a, 0x2a, 0xf5, 0x65, 0xa0, 0xc2, 0xd4, 0x18, 0x71, 0xfd, 0x6f, 0x0e,
	0x66, 0x6c, 0xcd, 0x6c, 0x2c, 0x83, 0x6a, 0xdf, 0x42, 0xf9, 0x0e, 0x5a, 0x07, 0xd8, 0x9e, 0xed,
	0x40, 0xb8, 0x1d, 0x0e, 0x81, 0xab, 0xef, 0xc0, 0x79, 0xd4, 0x1f, 0x4f, 0xb8, 0xbe, 0xd0, 0x7c,
	0x1a, 0x7a, 0xbe, 0xdd, 0xda, 0x9a, 0x60, 0x1f, 0x7e, 0xd2, 0x32, 0x0a, 0xa9, 0xb8, 0xcd, 0xa9,
	0x1f, 0xf5, 0xf0, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x73, 0xf5, 0x3a, 0x23, 0x0c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	DenomAuthorityMetadata(ctx context.Context, in *QueryDenomAuthorityMetadataRequest, opts ...grpc.CallOption) (*QueryDenomAuthorityMetadataResponse, error)
	DenomsFromCreator(ctx context.Context, in *QueryDenomsFromCreatorRequest, opts ...grpc.CallOption) (*QueryDenomsFromCreatorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DenomAuthorityMetadata(ctx context.Context, in *QueryDenomAuthorityMetadataRequest, opts ...grpc.CallOption) (*QueryDenomAuthorityMetadataResponse, error) {
	out := new(QueryDenomAuthorityMetadataResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Query/DenomAuthorityMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomsFromCreator(ctx context.Context, in *QueryDenomsFromCreatorRequest, opts ...grpc.CallOption) (*QueryDenomsFromCreatorResponse, error) {
	out := new(QueryDenomsFromCreatorResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Query/DenomsFromCreator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	DenomAuthorityMetadata(context.Context, *QueryDenomAuthorityMetadataRequest) (*QueryDenomAuthorityMetadataResponse, error)
	DenomsFromCreator(context.Context, *QueryDenomsFromCreatorRequest) (*QueryDenomsFromCreatorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DenomAuthorityMetadata(ctx context.Context, req *QueryDenomAuthorityMetadataRequest) (*QueryDenomAuthorityMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomAuthorityMetadata not implemented")
}
func (*UnimplementedQueryServer) DenomsFromCreator(ctx context.Context, req *QueryDenomsFromCreatorRequest) (*QueryDenomsFromCreatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomsFromCreator not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DenomAuthorityMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDenomAuthorityMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomAuthorityMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Query/DenomAuthorityMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomAuthorityMetadata(ctx, req.(*QueryDenomAuthorityMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomsFromCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDenomsFromCreatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomsFromCreator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Query/DenomsFromCreator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomsFromCreator(ctx, req.(*QueryDenomsFromCreatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "retrochain.tokenfactory.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DenomAuthorityMetadata",
			Handler:    _Query_DenomAuthorityMetadata_Handler,
		},
		{
			MethodName: "DenomsFromCreator",
			Handler:    _Query_DenomsFromCreator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrochain/tokenfactory/v1/query.proto",
}
