// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: retrochain/tokenfactory/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateDenom struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Subdenom             string   `protobuf:"bytes,2,opt,name=subdenom,proto3" json:"subdenom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateDenom) Reset()         { *m = MsgCreateDenom{} }
func (m *MsgCreateDenom) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDenom) ProtoMessage()    {}
func (*MsgCreateDenom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{0}
}
func (m *MsgCreateDenom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateDenom.Unmarshal(m, b)
}
func (m *MsgCreateDenom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateDenom.Marshal(b, m, deterministic)
}
func (m *MsgCreateDenom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDenom.Merge(m, src)
}
func (m *MsgCreateDenom) XXX_Size() int {
	return xxx_messageInfo_MsgCreateDenom.Size(m)
}
func (m *MsgCreateDenom) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDenom.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDenom proto.InternalMessageInfo

func (m *MsgCreateDenom) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCreateDenom) GetSubdenom() string {
	if m != nil {
		return m.Subdenom
	}
	return ""
}

type MsgCreateDenomResponse struct {
	NewDenom             string   `protobuf:"bytes,1,opt,name=new_denom,json=newDenom,proto3" json:"new_denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgCreateDenomResponse) Reset()         { *m = MsgCreateDenomResponse{} }
func (m *MsgCreateDenomResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDenomResponse) ProtoMessage()    {}
func (*MsgCreateDenomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{1}
}
func (m *MsgCreateDenomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgCreateDenomResponse.Unmarshal(m, b)
}
func (m *MsgCreateDenomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgCreateDenomResponse.Marshal(b, m, deterministic)
}
func (m *MsgCreateDenomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDenomResponse.Merge(m, src)
}
func (m *MsgCreateDenomResponse) XXX_Size() int {
	return xxx_messageInfo_MsgCreateDenomResponse.Size(m)
}
func (m *MsgCreateDenomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDenomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDenomResponse proto.InternalMessageInfo

func (m *MsgCreateDenomResponse) GetNewDenom() string {
	if m != nil {
		return m.NewDenom
	}
	return ""
}

type MsgMint struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// amount is a coin string like "123factory/<creator>/<subdenom>".
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// mint_to_address defaults to sender when empty.
	MintToAddress        string   `protobuf:"bytes,3,opt,name=mint_to_address,json=mintToAddress,proto3" json:"mint_to_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMint) Reset()         { *m = MsgMint{} }
func (m *MsgMint) String() string { return proto.CompactTextString(m) }
func (*MsgMint) ProtoMessage()    {}
func (*MsgMint) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{2}
}
func (m *MsgMint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMint.Unmarshal(m, b)
}
func (m *MsgMint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMint.Marshal(b, m, deterministic)
}
func (m *MsgMint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMint.Merge(m, src)
}
func (m *MsgMint) XXX_Size() int {
	return xxx_messageInfo_MsgMint.Size(m)
}
func (m *MsgMint) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMint.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMint proto.InternalMessageInfo

func (m *MsgMint) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgMint) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgMint) GetMintToAddress() string {
	if m != nil {
		return m.MintToAddress
	}
	return ""
}

type MsgMintResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMintResponse) Reset()         { *m = MsgMintResponse{} }
func (m *MsgMintResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintResponse) ProtoMessage()    {}
func (*MsgMintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{3}
}
func (m *MsgMintResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMintResponse.Unmarshal(m, b)
}
func (m *MsgMintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMintResponse.Marshal(b, m, deterministic)
}
func (m *MsgMintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintResponse.Merge(m, src)
}
func (m *MsgMintResponse) XXX_Size() int {
	return xxx_messageInfo_MsgMintResponse.Size(m)
}
func (m *MsgMintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintResponse proto.InternalMessageInfo

type MsgBurn struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// amount is a coin string like "123factory/<creator>/<subdenom>".
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// burn_from_address defaults to sender when empty.
	BurnFromAddress      string   `protobuf:"bytes,3,opt,name=burn_from_address,json=burnFromAddress,proto3" json:"burn_from_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBurn) Reset()         { *m = MsgBurn{} }
func (m *MsgBurn) String() string { return proto.CompactTextString(m) }
func (*MsgBurn) ProtoMessage()    {}
func (*MsgBurn) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{4}
}
func (m *MsgBurn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBurn.Unmarshal(m, b)
}
func (m *MsgBurn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBurn.Marshal(b, m, deterministic)
}
func (m *MsgBurn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurn.Merge(m, src)
}
func (m *MsgBurn) XXX_Size() int {
	return xxx_messageInfo_MsgBurn.Size(m)
}
func (m *MsgBurn) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurn.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurn proto.InternalMessageInfo

func (m *MsgBurn) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgBurn) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgBurn) GetBurnFromAddress() string {
	if m != nil {
		return m.BurnFromAddress
	}
	return ""
}

type MsgBurnResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBurnResponse) Reset()         { *m = MsgBurnResponse{} }
func (m *MsgBurnResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBurnResponse) ProtoMessage()    {}
func (*MsgBurnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{5}
}
func (m *MsgBurnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBurnResponse.Unmarshal(m, b)
}
func (m *MsgBurnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBurnResponse.Marshal(b, m, deterministic)
}
func (m *MsgBurnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnResponse.Merge(m, src)
}
func (m *MsgBurnResponse) XXX_Size() int {
	return xxx_messageInfo_MsgBurnResponse.Size(m)
}
func (m *MsgBurnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnResponse proto.InternalMessageInfo

type MsgChangeAdmin struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Denom                string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	NewAdmin             string   `protobuf:"bytes,3,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgChangeAdmin) Reset()         { *m = MsgChangeAdmin{} }
func (m *MsgChangeAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgChangeAdmin) ProtoMessage()    {}
func (*MsgChangeAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{6}
}
func (m *MsgChangeAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgChangeAdmin.Unmarshal(m, b)
}
func (m *MsgChangeAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgChangeAdmin.Marshal(b, m, deterministic)
}
func (m *MsgChangeAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeAdmin.Merge(m, src)
}
func (m *MsgChangeAdmin) XXX_Size() int {
	return xxx_messageInfo_MsgChangeAdmin.Size(m)
}
func (m *MsgChangeAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeAdmin proto.InternalMessageInfo

func (m *MsgChangeAdmin) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgChangeAdmin) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgChangeAdmin) GetNewAdmin() string {
	if m != nil {
		return m.NewAdmin
	}
	return ""
}

type MsgChangeAdminResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgChangeAdminResponse) Reset()         { *m = MsgChangeAdminResponse{} }
func (m *MsgChangeAdminResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeAdminResponse) ProtoMessage()    {}
func (*MsgChangeAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0d0e6dfa3cb2d72, []int{7}
}
func (m *MsgChangeAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgChangeAdminResponse.Unmarshal(m, b)
}
func (m *MsgChangeAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgChangeAdminResponse.Marshal(b, m, deterministic)
}
func (m *MsgChangeAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeAdminResponse.Merge(m, src)
}
func (m *MsgChangeAdminResponse) XXX_Size() int {
	return xxx_messageInfo_MsgChangeAdminResponse.Size(m)
}
func (m *MsgChangeAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeAdminResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateDenom)(nil), "retrochain.tokenfactory.v1.MsgCreateDenom")
	proto.RegisterType((*MsgCreateDenomResponse)(nil), "retrochain.tokenfactory.v1.MsgCreateDenomResponse")
	proto.RegisterType((*MsgMint)(nil), "retrochain.tokenfactory.v1.MsgMint")
	proto.RegisterType((*MsgMintResponse)(nil), "retrochain.tokenfactory.v1.MsgMintResponse")
	proto.RegisterType((*MsgBurn)(nil), "retrochain.tokenfactory.v1.MsgBurn")
	proto.RegisterType((*MsgBurnResponse)(nil), "retrochain.tokenfactory.v1.MsgBurnResponse")
	proto.RegisterType((*MsgChangeAdmin)(nil), "retrochain.tokenfactory.v1.MsgChangeAdmin")
	proto.RegisterType((*MsgChangeAdminResponse)(nil), "retrochain.tokenfactory.v1.MsgChangeAdminResponse")
}

func init() {
	proto.RegisterFile("retrochain/tokenfactory/v1/tx.proto", fileDescriptor_d0d0e6dfa3cb2d72)
}

var fileDescriptor_d0d0e6dfa3cb2d72 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0x15, 0xca, 0x2d, 0x5c, 0x23, 0xa8, 0x1a, 0x5d, 0x5d, 0x42, 0x18, 0xe0, 0xe6, 0x2e,
	0x57, 0x41, 0x24, 0xb4, 0xa8, 0x12, 0xea, 0x44, 0x4b, 0xc5, 0x96, 0xa5, 0x30, 0x20, 0x96, 0xc8,
	0x6d, 0xdc, 0x34, 0x42, 0xb6, 0x2b, 0xdb, 0xe9, 0x9f, 0x0d, 0x31, 0xf2, 0x04, 0x4c, 0x3c, 0x43,
	0x07, 0x1e, 0x02, 0x24, 0x26, 0x5e, 0xa2, 0xaf, 0x81, 0x1c, 0xbb, 0x4d, 0x02, 0x2a, 0x29, 0xd5,
	0x5d, 0xaa, 0x1c, 0xfb, 0x3b, 0xc7, 0xfe, 0x1d, 0x7f, 0xa7, 0xe0, 0x92, 0x21, 0xc1, 0xe8, 0x78,
	0x0a, 0x13, 0xe2, 0x0b, 0xfa, 0x01, 0x91, 0x09, 0x1c, 0x0b, 0xca, 0x56, 0xfe, 0xbc, 0xe5, 0x8b,
	0xa5, 0x37, 0x63, 0x54, 0x50, 0xd3, 0xce, 0x45, 0x5e, 0x51, 0xe4, 0xcd, 0x5b, 0x76, 0x13, 0xe2,
	0x84, 0x50, 0x3f, 0xfb, 0x55, 0x72, 0xfb, 0xfe, 0x98, 0x72, 0x4c, 0xb9, 0x8f, 0x79, 0x2c, 0xcb,
	0x60, 0x1e, 0xeb, 0x8d, 0x07, 0x6a, 0x23, 0xcc, 0x22, 0x5f, 0x05, 0x6a, 0xcb, 0xf9, 0x62, 0x80,
	0x7b, 0x01, 0x8f, 0x5f, 0x31, 0x04, 0x05, 0x1a, 0x20, 0x42, 0xb1, 0xf9, 0x0c, 0xd4, 0x39, 0x22,
	0x11, 0x62, 0x96, 0xf1, 0xd8, 0xb8, 0x3a, 0xed, 0x5b, 0xbf, 0xbe, 0x3d, 0x3d, 0xd3, 0x49, 0xbd,
	0x28, 0x62, 0x88, 0xf3, 0x37, 0x82, 0x25, 0x24, 0x1e, 0x6a, 0x9d, 0x69, 0x83, 0xdb, 0x3c, 0x1d,
	0x45, 0x32, 0xdb, 0xba, 0x21, 0x73, 0x86, 0xbb, 0xb8, 0xfb, 0xe2, 0xd3, 0x66, 0xed, 0x6a, 0xe1,
	0xe7, 0xcd, 0xda, 0xbd, 0x2a, 0x80, 0x2f, 0xcb, 0xe8, 0xe5, 0x7b, 0x38, 0x1d, 0x70, 0x5e, 0x5e,
	0x19, 0x22, 0x3e, 0xa3, 0x84, 0x23, 0xf3, 0x21, 0x38, 0x25, 0x68, 0x11, 0xaa, 0x03, 0x0d, 0x75,
	0x20, 0x41, 0x0b, 0x95, 0xf6, 0xdd, 0x00, 0xb7, 0x02, 0x1e, 0x07, 0x09, 0x11, 0x47, 0xa0, 0x9c,
	0x83, 0x3a, 0xc4, 0x34, 0x25, 0x42, 0x83, 0xe8, 0xc8, 0x7c, 0x09, 0x1a, 0x38, 0x21, 0x22, 0x14,
	0x34, 0x84, 0x2a, 0xd1, 0xaa, 0x55, 0x94, 0xbc, 0x2b, 0x13, 0xde, 0x52, 0xbd, 0xd8, 0x6d, 0xfd,
	0xd1, 0x88, 0x8b, 0x7f, 0x36, 0x42, 0x5e, 0xdf, 0x69, 0x82, 0x86, 0xfe, 0xdc, 0xa2, 0x3b, 0x3f,
	0x15, 0x5d, 0x3f, 0x65, 0xe4, 0x1a, 0xe9, 0x06, 0xa0, 0x39, 0x4a, 0x19, 0x09, 0x27, 0x8c, 0xe2,
	0x83, 0xf9, 0x1a, 0x32, 0xe5, 0x35, 0xa3, 0xf8, 0x38, 0x42, 0x89, 0xa0, 0x09, 0xe5, 0xe7, 0x8e,
	0xf0, 0x87, 0x76, 0xe4, 0x14, 0x92, 0x18, 0xf5, 0x22, 0x9c, 0x1c, 0x03, 0x7a, 0x06, 0x4e, 0x8a,
	0x76, 0x54, 0x81, 0xd9, 0x51, 0xbe, 0x81, 0xb2, 0x68, 0x25, 0x9e, 0x74, 0x54, 0x76, 0xfc, 0xff,
	0x5a, 0x38, 0xbf, 0xb8, 0x63, 0x29, 0x0b, 0xe7, 0x2b, 0x5b, 0xca, 0xf6, 0xd7, 0x1a, 0xa8, 0x05,
	0x3c, 0x36, 0x31, 0xb8, 0x53, 0x9c, 0x3d, 0xd7, 0xdb, 0x3f, 0xf2, 0x5e, 0x79, 0x1a, 0xec, 0xf6,
	0xe1, 0xda, 0xdd, 0xe4, 0xbc, 0x03, 0x37, 0xb3, 0xc1, 0xb8, 0xac, 0xc8, 0x95, 0x22, 0xfb, 0xc9,
	0x01, 0xa2, 0x62, 0xe5, 0xcc, 0x94, 0x55, 0x95, 0xa5, 0xa8, 0xb2, 0x72, 0xd1, 0x10, 0x59, 0x8b,
	0x0a, 0x66, 0xa8, 0x6c, 0x51, 0xae, 0xad, 0x6e, 0xd1, 0xdf, 0x2f, 0x63, 0x9f, 0x7c, 0xdc, 0xac,
	0x5d, 0xa3, 0x7f, 0xf1, 0xfe, 0xd1, 0xfe, 0x67, 0x16, 0xab, 0x19, 0xe2, 0xa3, 0x7a, 0xf6, 0x17,
	0xfa, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0x5e, 0x0d, 0x53, 0xcc, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateDenom(ctx context.Context, in *MsgCreateDenom, opts ...grpc.CallOption) (*MsgCreateDenomResponse, error)
	Mint(ctx context.Context, in *MsgMint, opts ...grpc.CallOption) (*MsgMintResponse, error)
	Burn(ctx context.Context, in *MsgBurn, opts ...grpc.CallOption) (*MsgBurnResponse, error)
	ChangeAdmin(ctx context.Context, in *MsgChangeAdmin, opts ...grpc.CallOption) (*MsgChangeAdminResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateDenom(ctx context.Context, in *MsgCreateDenom, opts ...grpc.CallOption) (*MsgCreateDenomResponse, error) {
	out := new(MsgCreateDenomResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Msg/CreateDenom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Mint(ctx context.Context, in *MsgMint, opts ...grpc.CallOption) (*MsgMintResponse, error) {
	out := new(MsgMintResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Msg/Mint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Burn(ctx context.Context, in *MsgBurn, opts ...grpc.CallOption) (*MsgBurnResponse, error) {
	out := new(MsgBurnResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Msg/Burn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChangeAdmin(ctx context.Context, in *MsgChangeAdmin, opts ...grpc.CallOption) (*MsgChangeAdminResponse, error) {
	out := new(MsgChangeAdminResponse)
	err := c.cc.Invoke(ctx, "/retrochain.tokenfactory.v1.Msg/ChangeAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateDenom(context.Context, *MsgCreateDenom) (*MsgCreateDenomResponse, error)
	Mint(context.Context, *MsgMint) (*MsgMintResponse, error)
	Burn(context.Context, *MsgBurn) (*MsgBurnResponse, error)
	ChangeAdmin(context.Context, *MsgChangeAdmin) (*MsgChangeAdminResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateDenom(ctx context.Context, req *MsgCreateDenom) (*MsgCreateDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDenom not implemented")
}
func (*UnimplementedMsgServer) Mint(ctx context.Context, req *MsgMint) (*MsgMintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mint not implemented")
}
func (*UnimplementedMsgServer) Burn(ctx context.Context, req *MsgBurn) (*MsgBurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Burn not implemented")
}
func (*UnimplementedMsgServer) ChangeAdmin(ctx context.Context, req *MsgChangeAdmin) (*MsgChangeAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAdmin not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDenom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Msg/CreateDenom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDenom(ctx, req.(*MsgCreateDenom))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Mint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Mint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Msg/Mint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Mint(ctx, req.(*MsgMint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Burn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Burn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Msg/Burn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Burn(ctx, req.(*MsgBurn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChangeAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/retrochain.tokenfactory.v1.Msg/ChangeAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeAdmin(ctx, req.(*MsgChangeAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "retrochain.tokenfactory.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDenom",
			Handler:    _Msg_CreateDenom_Handler,
		},
		{
			MethodName: "Mint",
			Handler:    _Msg_Mint_Handler,
		},
		{
			MethodName: "Burn",
			Handler:    _Msg_Burn_Handler,
		},
		{
			MethodName: "ChangeAdmin",
			Handler:    _Msg_ChangeAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retrochain/tokenfactory/v1/tx.proto",
}
